In [ ]:
!pip install wandb

In [29]:
import wandb
import pandas as pd
import numpy as np

Marcas:


1 = Adidas	
2 = Animale	
3 = Aramis	
4 = Arezzo  
5 = Besni  
6 = Brooks   
7 = field  
8 = C&A	  
9 = Caedu  
10 = Carmen Steffens  
11 = Centauro	
12 = Cia. Marítima	
13 = Colcci	
14 = Dafiti	
15 = Dakota   
16 = Decathlon	
16 = DeMillus  
17 = Di Santinni  	
18 = Dumond  
19 = Ellus	
20 = Farm	
21 = Fórum 	
22 = Havaianas	
23 = Hering	
24 = Hope	
25 = Ipanema	
26 = John John	
27 = Kyly	
28 = Le Lis Blanc	
29 = Leader	
30 = Lojas Avenida	
31 = Lojas Pompéia	
32 = Lupo	
33 = Malwee	
34 = Marisa	
35 = Marisol  
36 = Melissa	
37 = Moleca	
38 = Netshoes	
39 = Nike 	
40 = Olympikus	
41 = Osklen	
42 = Pernambucanas	
43 = Puket	
44 = Renner	
45 =Riachuelo	
46 = Sawary	
47 = TNG	
48 = Torra	
49 = Youcom	
50 = Zara

Legenda para as colunas:

**antiss** =Antissuborno,corrupção e apresentação de informações falsas  
**AV**= Assédio e violência  
**BA** = Bem-estar animal  
**BC** = Biodiversidade e conservação  
**DRML** = Direitos relacionados à maternidade e licença-parental  
**desc** = Discriminação  
**DI** = Diversidade e inclusão  
**EEG**= Energia e emissões de gases de efeito estufa  
**EC** =Engajamento com a comunidade  
**ES** = Equiparação salarial  
**FAFP** = Férias anuais e feriados públicos  
**HTID** = Horas de trabalho e intervalos de descanso  
**LADON** = Liberdade de associação, direito de organização e negociação coletiva  
**LSR** = Lista de substâncias restritas  
**RE** = Resíduos e/ou reciclagem (embalagens/escritório/varejo)  
**RP** =Resíduos e/ou reciclagem (produtos/têxteis)   
**SBF** = Salários e benefícios financeiros (ex.: bônus, seguro,   previdência complementar, pensão)  
**SS** = Saúde e segurança  
**SMB** = Saúde mental e bem-estar  
**UA** = Uso de água

In [3]:
# importing the dataset
url01 = 'https://raw.githubusercontent.com/juliaguardiani/test_ITM_BRASIL/main/politicaDireitosHumanoMeioAmbiente.csv'
url02 = 'https://raw.githubusercontent.com/juliaguardiani/test_ITM_BRASIL/main/politicaDireitoHumanosMeioAmbienteFornecimento.csv'
url03 = 'https://raw.githubusercontent.com/juliaguardiani/test_ITM_BRASIL/main/informacoesDireitosHumanosMeioAmbiente.csv'

df01 = pd.read_csv(url01)
df02 = pd.read_csv(url02)
df03 = pd.read_csv(url03)

In [6]:
df01

,marca,antiss,AV,BA,BC,DRML,dresc,DI,EEG,EC,...,FAFP,HTID,LADON,LSR,RE,RP,SBF,SS,SMB,UA
0,1,"0,25","0,25","0,25",0,"0,25","0,25","0,25","0,25","0,25",...,0,"0,25","0,25","0,25",0,0,"0,25","0,25","0,25",0
1,2,"0,25","0,25",0,"0,25","0,25","0,25","0,25","0,25",0,...,"0,25","0,25","0,25",0,"0,25","0,25","0,25","0,25",0,"0,25"
2,3,0,"0,25",0,0,"0,25","0,25","0,25",0,0,...,"0,25","0,25","0,25",0,0,0,"0,25",0,0,0
3,4,"0,25","0,25",0,"0,25",0,"0,25","0,25","0,25","0,25",...,0,0,"0,25","0,25","0,25","0,25",0,"0,25","0,25",0
4,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,7,"0,25","0,25","0,25",0,"0,25","0,25","0,25","0,25","0,25",...,"0,25","0,25","0,25","0,25","0,25","0,25","0,25","0,25","0,25","0,25"
7,8,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,10,"0,25","0,25",0,0,0,"0,25",0,0,0,...,0,0,"0,25",0,0,0,"0,25",0,0,0
10,11,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,12,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,13,"0,25","0,25","0,25","0,25","0,25","0,25","0,25","0,25","0,25",...,"0,25","0,25","0,25","0,25","0,25",0,0,"0,25",0,"0,25"
13,14,"0,25","0,25",0,"0,25",0,"0,25",0,0,"0,25",...,0,0,"0,25",0,0,0,"0,25","0,25",0,0
14,15,"0,25",0,"0,25","0,25",0,0,0,"0,25","0,25",...,"0,25",0,0,"0,25","0,25",0,"0,25","0,25","0,25",0
15,16,0,0,0,0,0,0,"0,25",0,0,...,0,0,0,0,0,0,0,0,0,0
16,17,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,18,"0,25","0,25",0,0,0,"0,25","0,25",0,0,...,0,0,"0,25",0,0,0,0,"0,25",0,0
18,19,"0,25","0,25",0,0,0,"0,25",0,0,0,...,0,0,"0,25",0,"0,25",0,0,0,0,0
19,20,"0,25","0,25",0,"0,25","0,25","0,25","0,25","0,25",0,...,"0,25","0,25","0,25",0,"0,25","0,25","0,25","0,25",0,"0,25"
20,21,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,22,"0,25","0,25",0,"0,25","0,25","0,25",0,0,"0,25",...,"0,25","0,25","0,25","0,25","0,25","0,25","0,25","0,25",0,0
22,23,"0,25","0,25",0,"0,25","0,25","0,25","0,25","0,25","0,25",...,"0,25","0,25","0,25",0,0,"0,25","0,25","0,25",0,"0,25"
23,24,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,25,"0,25","0,25","0,25","0,25","0,25","0,25","0,25","0,25","0,25",...,"0,25","0,25","0,25","0,25","0,25","0,25","0,25","0,25",0,"0,25"
25,26,"0,25","0,25",0,0,"0,25","0,25",0,0,0,...,"0,25","0,25","0,25",0,"0,25",0,"0,25","0,25",0,0
26,27,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,28,"0,25","0,25",0,0,"0,25","0,25",0,0,0,...,"0,25","0,25","0,25",0,"0,25",0,"0,25","0,25",0,0
28,29,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,30,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
30,31,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
31,32,"0,25",0,"0,25",0,"0,25",0,0,0,"0,25",...,"0,25","0,25","0,25",0,"0,25","0,25","0,25","0,25",0,0
32,33,"0,25","0,25","0,25","0,25","0,25","0,25","0,25",0,"0,25",...,"0,25","0,25","0,25","0,25","0,25","0,25","0,25","0,25","0,25",0
33,34,"0,25","0,25",0,0,0,"0,25",0,0,"0,25",...,0,0,0,"0,25",0,0,0,"0,25",0,0
34,35,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35,36,"0,25","0,25","0,25","0,25","0,25","0,25","0,25","0,25","0,25",...,"0,25","0,25","0,25","0,25","0,25","0,25","0,25","0,25",0,"0,25"
36,37,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
37,38,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
38,39,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
39,40,0,"0,25",0,0,0,"0,25","0,25",0,0,...,0,0,0,0,0,0,0,0,0,0
40,41,"0,25","0,25",0,"0,25","0,25","0,25",0,0,"0,25",...,"0,25","0,25","0,25","0,25","0,25","0,25","0,25","0,25","0,25",0
41,42,"0,25","0,25",0,0,"0,25","0,25","0,25","0,25","0,25",...,"0,25","0,25","0,25","0,25","0,25","0,25","0,25","0,25",0,"0,25"
42,43,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
43,44,"0,25","0,25",0,"0,25",0,"0,25","0,25","0,25","0,25",...,0,0,"0,25","0,25","0,25","0,25",0,"0,25",0,"0,25"
44,45,"0,25","0,25",0,"0,25","0,25","0,25","0,25","0,25","0,25",...,"0,25","0,25","0,25",0,0,0,"0,25","0,25","0,25","0,25"
45,46,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
46,47,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
47,48,"0,25","0,25",0,"0,25",0,"0,25",0,"0,25","0,25",...,0,0,0,0,"0,25",0,"0,25",0,0,"0,25"
48,49,"0,25","0,25",0,"0,25",0,"0,25","0,25","0,25","0,25",...,0,0,"0,25","0,25","0,25","0,25",0,"0,25",0,"0,25"
49,50,"0,25","0,25","0,25","0,25",0,"0,25","0,25","0,25","0,25",...,0,"0,25","0,25","0,25","0,25","0,25","0,25","0,25",0,"0,25"

SIGLA	NOME ORIGINAL

marca = marca  
ACA = Antissuborno, corrupção e apresentação de informações falsas  
AV = Assédio e violência  
BC = Biodiversidade e conservação  
CH = Condições de habitação/dormitórios  
CTE = Contratos e termos empregatícios (incluindo aviso prévio, demissão e ação disciplinar)  
DM = Direitos relacionados à maternidade e licença-parental  
discrim = Discriminação  
ELT = Efluentes líquidos e tratamento  
EEG = Energia e emissões de gases de efeito estufa  
EC = Engajamento com a comunidade  
ES = Equiparação salarial   
FF = Férias anuais e feriados públicos  
HI = Horas de trabalho e intervalos de descanso  
LDN = Liberdade de associação, direito de organização e negociação coletiva   
SR = Lista de substâncias restritas na produção  
MEM = Mão de obra estrangeira e migrante  
PHE = Pagamento de horas extras  
RR = Resíduos e/ou reciclagem (embalagens/escritório/varejo)  
RRP = Resíduos e/ou reciclagem (produtos/têxteis)  
SBF = Salários e benefícios financeiros (ex.: bônus, seguro, previdência complementar, pensão)  
SS = Saúde e segurança  
subc = Subcontratação  
TC = Trabalho de casa  
TEC = Trabalho escravo contemporâneo  
TI = Trabalho infantil   
usoAgua = Uso de água

In [4]:
# columns used 
columns02 = ['marca', 'ACA', 'AV', 'BC', 'CH', 'CTE', 'DM', 'discrim', 'ELT', 'EEG', 'EC', 'ES', 'FF', 'HI', 'LDN', 'SR',
             'MEM', 'PHE', 'RR', 'RRP', 'SBF', 'SS', 'subc', 'TC', 'TEC', 'TI', 'usoAgua']

income02 = pd.read_csv(url02, header=None, names=columns02, skiprows=[0])

income02.head()

,marca,ACA,AV,BC,CH,CTE,DM,discrim,ELT,EEG,...,PHE,RR,RRP,SBF,SS,subc,TC,TEC,TI,usoAgua
0,1,"0,25","0,25","0,25","0,25","0,25",0,"0,25","0,25","0,25",...,"0,25","0,25","0,25","0,25","0,25","0,25","0,25","0,25","0,25","0,25"
1,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,"0,25",0,0,0,0,0,"0,25",0,0,...,0,0,0,0,0,0,0,"0,25","0,25",0
3,4,"0,25","0,25","0,25",0,0,0,"0,25",0,0,...,0,0,0,0,"0,25",0,0,"0,25","0,25",0
4,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
# columns used 
columns03 = ['marca', 'ACA', 'AV', 'BA', 'BC', 'CH', 'CTE', 'DM', 'discrim', 'DI', 'ELT', 'EEG', 'EC', 'ES', 'FF', 
            'HI', 'LDN', 'SR', 'SRR', 'MEM', 'PHE', 'RR', 'RRP', 'SBF', 'SS', 'SMB', 'subc', 'TC', 'TEC', 'TI', 'usuAgua']

income03 = pd.read_csv(url03, header=None, names=columns03, skiprows=[0])

income03.head()

,marca,ACA,AV,BA,BC,CH,CTE,DM,discrim,DI,...,RR,RRP,SBF,SS,SMB,subc,TC,TEC,TI,usuAgua
0,1,"0,5","0,5","0,5","0,5","0,5","0,5","0,5","0,5","0,5",...,"0,5","0,5","0,5","0,5","0,5","0,5",0,"0,5","0,5","0,5"
1,2,"0,5","0,5",0,"0,5",0,"0,5","0,5","0,5","0,5",...,0,"0,5","0,5",0,"0,5",0,0,0,"0,5",0
2,3,"0,5","0,5",0,0,0,"0,5","0,5","0,5","0,5",...,0,0,0,"0,5","0,5",0,0,0,0,"0,5"
3,4,"0,5",0,"0,5","0,5",0,0,"0,5","0,5","0,5",...,"0,5","0,5",0,"0,5","0,5",0,0,0,"0,5",0
4,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [24]:
for col in df01.columns:
  df01[col] = df01[col].astype(str)
  df01[col] = df01[col].str.replace(',','.')

for col in income02.columns:
  income02[col] = income02[col].astype(str)
  income02[col] = income02[col].str.replace(',','.')

for col in income03.columns:
  income03[col] = income03[col].astype(str)
  income03[col] = income03[col].str.replace(',','.')

In [25]:
df01.head()

,marca,antiss,AV,BA,BC,DRML,dresc,DI,EEG,EC,...,FAFP,HTID,LADON,LSR,RE,RP,SBF,SS,SMB,UA
0,1,0.25,0.25,0.25,0,0.25,0.25,0.25,0.25,0.25,...,0,0.25,0.25,0.25,0,0,0.25,0.25,0.25,0
1,2,0.25,0.25,0,0.25,0.25,0.25,0.25,0.25,0,...,0.25,0.25,0.25,0,0.25,0.25,0.25,0.25,0,0.25
2,3,0,0.25,0,0,0.25,0.25,0.25,0,0,...,0.25,0.25,0.25,0,0,0,0.25,0,0,0
3,4,0.25,0.25,0,0.25,0,0.25,0.25,0.25,0.25,...,0,0,0.25,0.25,0.25,0.25,0,0.25,0.25,0
4,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [26]:
income02.head()

,marca,ACA,AV,BC,CH,CTE,DM,discrim,ELT,EEG,...,PHE,RR,RRP,SBF,SS,subc,TC,TEC,TI,usoAgua
0,1,0.25,0.25,0.25,0.25,0.25,0,0.25,0.25,0.25,...,0.25,0.25,0.25,0.25,0.25,0.25,0.25,0.25,0.25,0.25
1,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,0.25,0,0,0,0,0,0.25,0,0,...,0,0,0,0,0,0,0,0.25,0.25,0
3,4,0.25,0.25,0.25,0,0,0,0.25,0,0,...,0,0,0,0,0.25,0,0,0.25,0.25,0
4,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [27]:
income03.head()

,marca,ACA,AV,BA,BC,CH,CTE,DM,discrim,DI,...,RR,RRP,SBF,SS,SMB,subc,TC,TEC,TI,usuAgua
0,1,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...,0.5,0.5,0.5,0.5,0.5,0.5,0,0.5,0.5,0.5
1,2,0.5,0.5,0,0.5,0,0.5,0.5,0.5,0.5,...,0,0.5,0.5,0,0.5,0,0,0,0.5,0
2,3,0.5,0.5,0,0,0,0.5,0.5,0.5,0.5,...,0,0,0,0.5,0.5,0,0,0,0,0.5
3,4,0.5,0,0.5,0.5,0,0,0.5,0.5,0.5,...,0.5,0.5,0,0.5,0.5,0,0,0,0.5,0
4,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
pip install -U scikit-learn

In [45]:
from sklearn.cluster import KMeans

X_01= df01
kmeans = KMeans(n_clusters=3, random_state=0).fit(X_01)
kmeans.labels_

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0], dtype=int32)

In [46]:
 X_01['label'] = kmeans.predict(X_01)

In [47]:
X_01

,marca,antiss,AV,BA,BC,DRML,dresc,DI,EEG,EC,...,HTID,LADON,LSR,RE,RP,SBF,SS,SMB,UA,label
0,1,0.25,0.25,0.25,0,0.25,0.25,0.25,0.25,0.25,...,0.25,0.25,0.25,0,0,0.25,0.25,0.25,0,1
1,2,0.25,0.25,0,0.25,0.25,0.25,0.25,0.25,0,...,0.25,0.25,0,0.25,0.25,0.25,0.25,0,0.25,1
2,3,0,0.25,0,0,0.25,0.25,0.25,0,0,...,0.25,0.25,0,0,0,0.25,0,0,0,1
3,4,0.25,0.25,0,0.25,0,0.25,0.25,0.25,0.25,...,0,0.25,0.25,0.25,0.25,0,0.25,0.25,0,1
4,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
5,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
6,7,0.25,0.25,0.25,0,0.25,0.25,0.25,0.25,0.25,...,0.25,0.25,0.25,0.25,0.25,0.25,0.25,0.25,0.25,1
7,8,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
8,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
9,10,0.25,0.25,0,0,0,0.25,0,0,0,...,0,0.25,0,0,0,0.25,0,0,0,1
10,11,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
11,12,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
12,13,0.25,0.25,0.25,0.25,0.25,0.25,0.25,0.25,0.25,...,0.25,0.25,0.25,0.25,0,0,0.25,0,0.25,1
13,14,0.25,0.25,0,0.25,0,0.25,0,0,0.25,...,0,0.25,0,0,0,0.25,0.25,0,0,1
14,15,0.25,0,0.25,0.25,0,0,0,0.25,0.25,...,0,0,0.25,0.25,0,0.25,0.25,0.25,0,1
15,16,0,0,0,0,0,0,0.25,0,0,...,0,0,0,0,0,0,0,0,0,1
16,17,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
17,18,0.25,0.25,0,0,0,0.25,0.25,0,0,...,0,0.25,0,0,0,0,0.25,0,0,2
18,19,0.25,0.25,0,0,0,0.25,0,0,0,...,0,0.25,0,0.25,0,0,0,0,0,2
19,20,0.25,0.25,0,0.25,0.25,0.25,0.25,0.25,0,...,0.25,0.25,0,0.25,0.25,0.25,0.25,0,0.25,2
20,21,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
21,22,0.25,0.25,0,0.25,0.25,0.25,0,0,0.25,...,0.25,0.25,0.25,0.25,0.25,0.25,0.25,0,0,2
22,23,0.25,0.25,0,0.25,0.25,0.25,0.25,0.25,0.25,...,0.25,0.25,0,0,0.25,0.25,0.25,0,0.25,2
23,24,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
24,25,0.25,0.25,0.25,0.25,0.25,0.25,0.25,0.25,0.25,...,0.25,0.25,0.25,0.25,0.25,0.25,0.25,0,0.25,2
25,26,0.25,0.25,0,0,0.25,0.25,0,0,0,...,0.25,0.25,0,0.25,0,0.25,0.25,0,0,2
26,27,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
27,28,0.25,0.25,0,0,0.25,0.25,0,0,0,...,0.25,0.25,0,0.25,0,0.25,0.25,0,0,2
28,29,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
29,30,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
30,31,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
31,32,0.25,0,0.25,0,0.25,0,0,0,0.25,...,0.25,0.25,0,0.25,0.25,0.25,0.25,0,0,2
32,33,0.25,0.25,0.25,0.25,0.25,0.25,0.25,0,0.25,...,0.25,0.25,0.25,0.25,0.25,0.25,0.25,0.25,0,2
33,34,0.25,0.25,0,0,0,0.25,0,0,0.25,...,0,0,0.25,0,0,0,0.25,0,0,2
34,35,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35,36,0.25,0.25,0.25,0.25,0.25,0.25,0.25,0.25,0.25,...,0.25,0.25,0.25,0.25,0.25,0.25,0.25,0,0.25,0
36,37,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
37,38,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
38,39,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
39,40,0,0.25,0,0,0,0.25,0.25,0,0,...,0,0,0,0,0,0,0,0,0,0
40,41,0.25,0.25,0,0.25,0.25,0.25,0,0,0.25,...,0.25,0.25,0.25,0.25,0.25,0.25,0.25,0.25,0,0
41,42,0.25,0.25,0,0,0.25,0.25,0.25,0.25,0.25,...,0.25,0.25,0.25,0.25,0.25,0.25,0.25,0,0.25,0
42,43,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
43,44,0.25,0.25,0,0.25,0,0.25,0.25,0.25,0.25,...,0,0.25,0.25,0.25,0.25,0,0.25,0,0.25,0
44,45,0.25,0.25,0,0.25,0.25,0.25,0.25,0.25,0.25,...,0.25,0.25,0,0,0,0.25,0.25,0.25,0.25,0
45,46,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
46,47,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
47,48,0.25,0.25,0,0.25,0,0.25,0,0.25,0.25,...,0,0,0,0.25,0,0.25,0,0,0.25,0
48,49,0.25,0.25,0,0.25,0,0.25,0.25,0.25,0.25,...,0,0.25,0.25,0.25,0.25,0,0.25,0,0.25,0
49,50,0.25,0.25,0.25,0.25,0,0.25,0.25,0.25,0.25,...,0.25,0.25,0.25,0.25,0.25,0.25,0.25,0,0.25,0

In [48]:
kmeans.cluster_centers_

array([[4.25000000e+01, 1.25000000e-01, 1.40625000e-01, 3.12500000e-02,
        1.09375000e-01, 6.25000000e-02, 1.40625000e-01, 1.09375000e-01,
        1.09375000e-01, 1.25000000e-01, 6.25000000e-02, 6.25000000e-02,
        7.81250000e-02, 1.09375000e-01, 9.37500000e-02, 1.09375000e-01,
        9.37500000e-02, 9.37500000e-02, 1.09375000e-01, 3.12500000e-02,
        1.09375000e-01, 2.22044605e-16],
       [9.00000000e+00, 1.17647059e-01, 1.17647059e-01, 5.88235294e-02,
        7.35294118e-02, 7.35294118e-02, 1.17647059e-01, 1.02941176e-01,
        8.82352941e-02, 8.82352941e-02, 1.47058824e-02, 7.35294118e-02,
        7.35294118e-02, 1.17647059e-01, 7.35294118e-02, 7.35294118e-02,
        4.41176471e-02, 1.02941176e-01, 1.02941176e-01, 5.88235294e-02,
        4.41176471e-02, 1.00000000e+00],
       [2.60000000e+01, 1.61764706e-01, 1.47058824e-01, 4.41176471e-02,
        7.35294118e-02, 1.17647059e-01, 1.47058824e-01, 7.35294118e-02,
        4.41176471e-02, 8.82352941e-02, 5.88235294e-02, 1.17647059e-01,
        1.17647059e-01, 1.47058824e-01, 5.88235294e-02, 1.17647059e-01,
        8.82352941e-02, 1.17647059e-01, 1.47058824e-01, 1.47058824e-02,
        4.41176471e-02, 2.00000000e+00]])

In [49]:
X_01.to_csv('cluster_df01.csv',index=False)

In [54]:
X_02= income03
kmeans = KMeans(n_clusters=3, random_state=0).fit(X_02)
kmeans.labels_

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int32)

In [55]:
 X_02['label'] = kmeans.predict(X_02)

In [56]:
X_02

,marca,ACA,AV,BA,BC,CH,CTE,DM,discrim,DI,...,RRP,SBF,SS,SMB,subc,TC,TEC,TI,usuAgua,label
0,1,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...,0.5,0.5,0.5,0.5,0.5,0,0.5,0.5,0.5,0
1,2,0.5,0.5,0,0.5,0,0.5,0.5,0.5,0.5,...,0.5,0.5,0,0.5,0,0,0,0.5,0,0
2,3,0.5,0.5,0,0,0,0.5,0.5,0.5,0.5,...,0,0,0.5,0.5,0,0,0,0,0.5,0
3,4,0.5,0,0.5,0.5,0,0,0.5,0.5,0.5,...,0.5,0,0.5,0.5,0,0,0,0.5,0,0
4,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,7,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0
7,8,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,10,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,11,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,12,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,13,0.5,0,0.5,0.5,0.5,0,0,0.5,0.5,...,0,0.5,0.5,0.5,0.5,0,0,0,0.5,0
13,14,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,15,0.5,0,0.5,0.5,0.5,0,0,0,0.5,...,0.5,0.5,0.5,0.5,0,0,0.5,0,0,0
15,16,0,0,0,0,0,0,0,0,0,...,0.5,0,0,0.5,0,0,0,0,0.5,0
16,17,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
17,18,0,0,0,0,0,0,0,0,0.5,...,0,0,0,0,0,0,0,0.5,0,2
18,19,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
19,20,0.5,0.5,0,0.5,0,0.5,0.5,0.5,0.5,...,0.5,0.5,0,0.5,0,0,0,0.5,0,2
20,21,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
21,22,0.5,0.5,0,0.5,0,0,0,0.5,0.5,...,0.5,0.5,0.5,0,0,0,0,0.5,0.5,2
22,23,0,0,0,0.5,0,0.5,0.5,0,0.5,...,0.5,0.5,0.5,0.5,0,0,0,0.5,0.5,2
23,24,0,0,0,0,0,0,0,0,0,...,0,0,0.5,0.5,0,0,0,0,0,2
24,25,0.5,0.5,0.5,0.5,0,0.5,0,0.5,0.5,...,0.5,0.5,0.5,0,0,0,0,0,0.5,2
25,26,0,0,0,0.5,0,0,0,0,0,...,0.5,0,0.5,0,0,0,0,0.5,0,2
26,27,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
27,28,0,0,0,0.5,0,0,0,0,0,...,0.5,0,0.5,0,0,0,0,0.5,0,2
28,29,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
29,30,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
30,31,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
31,32,0,0,0,0.5,0,0.5,0.5,0,0,...,0.5,0.5,0.5,0.5,0,0,0,0,0.5,2
32,33,0.5,0.5,0.5,0.5,0.5,0.5,0,0,0.5,...,0.5,0.5,0.5,0.5,0.5,0,0,0.5,0.5,2
33,34,0.5,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.5,0.5,1
34,35,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
35,36,0.5,0.5,0.5,0.5,0,0.5,0,0.5,0.5,...,0.5,0.5,0.5,0,0,0,0,0,0.5,1
36,37,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
37,38,0.5,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
38,39,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
39,40,0,0,0,0,0,0,0,0,0,...,0.5,0,0.5,0,0,0,0,0.5,0.5,1
40,41,0.5,0.5,0,0.5,0,0,0,0.5,0.5,...,0.5,0.5,0.5,0.5,0,0,0,0.5,0.5,1
41,42,0.5,0.5,0,0,0.5,0.5,0.5,0.5,0.5,...,0,0,0.5,0,0,0,0.5,0.5,0.5,1
42,43,0,0,0,0,0,0,0,0,0,...,0.5,0,0,0,0,0,0,0,0,1
43,44,0.5,0.5,0.5,0.5,0,0,0.5,0.5,0.5,...,0.5,0.5,0.5,0.5,0.5,0,0.5,0.5,0.5,1
44,45,0.5,0.5,0,0.5,0,0.5,0.5,0.5,0.5,...,0.5,0.5,0.5,0.5,0.5,0,0.5,0.5,0.5,1
45,46,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
46,47,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
47,48,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
48,49,0.5,0.5,0.5,0.5,0,0,0.5,0.5,0.5,...,0.5,0.5,0.5,0.5,0.5,0,0.5,0.5,0.5,1
49,50,0.5,0.5,0.5,0.5,0,0.5,0.5,0.5,0.5,...,0.5,0.5,0.5,0.5,0.5,0,0.5,0.5,0.5,1

In [58]:
X_02.to_csv('income02.csv',index=False)

In [59]:
X_03= income03
kmeans = KMeans(n_clusters=3, random_state=0).fit(X_03)
kmeans.labels_

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int32)

In [61]:
 X_03['label'] = kmeans.predict(X_03)

In [62]:
X_03

,marca,ACA,AV,BA,BC,CH,CTE,DM,discrim,DI,...,RRP,SBF,SS,SMB,subc,TC,TEC,TI,usuAgua,label
0,1,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...,0.5,0.5,0.5,0.5,0.5,0,0.5,0.5,0.5,0
1,2,0.5,0.5,0,0.5,0,0.5,0.5,0.5,0.5,...,0.5,0.5,0,0.5,0,0,0,0.5,0,0
2,3,0.5,0.5,0,0,0,0.5,0.5,0.5,0.5,...,0,0,0.5,0.5,0,0,0,0,0.5,0
3,4,0.5,0,0.5,0.5,0,0,0.5,0.5,0.5,...,0.5,0,0.5,0.5,0,0,0,0.5,0,0
4,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,7,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0
7,8,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,10,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,11,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,12,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,13,0.5,0,0.5,0.5,0.5,0,0,0.5,0.5,...,0,0.5,0.5,0.5,0.5,0,0,0,0.5,0
13,14,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,15,0.5,0,0.5,0.5,0.5,0,0,0,0.5,...,0.5,0.5,0.5,0.5,0,0,0.5,0,0,0
15,16,0,0,0,0,0,0,0,0,0,...,0.5,0,0,0.5,0,0,0,0,0.5,0
16,17,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
17,18,0,0,0,0,0,0,0,0,0.5,...,0,0,0,0,0,0,0,0.5,0,2
18,19,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
19,20,0.5,0.5,0,0.5,0,0.5,0.5,0.5,0.5,...,0.5,0.5,0,0.5,0,0,0,0.5,0,2
20,21,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
21,22,0.5,0.5,0,0.5,0,0,0,0.5,0.5,...,0.5,0.5,0.5,0,0,0,0,0.5,0.5,2
22,23,0,0,0,0.5,0,0.5,0.5,0,0.5,...,0.5,0.5,0.5,0.5,0,0,0,0.5,0.5,2
23,24,0,0,0,0,0,0,0,0,0,...,0,0,0.5,0.5,0,0,0,0,0,2
24,25,0.5,0.5,0.5,0.5,0,0.5,0,0.5,0.5,...,0.5,0.5,0.5,0,0,0,0,0,0.5,2
25,26,0,0,0,0.5,0,0,0,0,0,...,0.5,0,0.5,0,0,0,0,0.5,0,2
26,27,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
27,28,0,0,0,0.5,0,0,0,0,0,...,0.5,0,0.5,0,0,0,0,0.5,0,2
28,29,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
29,30,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
30,31,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
31,32,0,0,0,0.5,0,0.5,0.5,0,0,...,0.5,0.5,0.5,0.5,0,0,0,0,0.5,2
32,33,0.5,0.5,0.5,0.5,0.5,0.5,0,0,0.5,...,0.5,0.5,0.5,0.5,0.5,0,0,0.5,0.5,2
33,34,0.5,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.5,0.5,1
34,35,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
35,36,0.5,0.5,0.5,0.5,0,0.5,0,0.5,0.5,...,0.5,0.5,0.5,0,0,0,0,0,0.5,1
36,37,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
37,38,0.5,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
38,39,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
39,40,0,0,0,0,0,0,0,0,0,...,0.5,0,0.5,0,0,0,0,0.5,0.5,1
40,41,0.5,0.5,0,0.5,0,0,0,0.5,0.5,...,0.5,0.5,0.5,0.5,0,0,0,0.5,0.5,1
41,42,0.5,0.5,0,0,0.5,0.5,0.5,0.5,0.5,...,0,0,0.5,0,0,0,0.5,0.5,0.5,1
42,43,0,0,0,0,0,0,0,0,0,...,0.5,0,0,0,0,0,0,0,0,1
43,44,0.5,0.5,0.5,0.5,0,0,0.5,0.5,0.5,...,0.5,0.5,0.5,0.5,0.5,0,0.5,0.5,0.5,1
44,45,0.5,0.5,0,0.5,0,0.5,0.5,0.5,0.5,...,0.5,0.5,0.5,0.5,0.5,0,0.5,0.5,0.5,1
45,46,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
46,47,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
47,48,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
48,49,0.5,0.5,0.5,0.5,0,0,0.5,0.5,0.5,...,0.5,0.5,0.5,0.5,0.5,0,0.5,0.5,0.5,1
49,50,0.5,0.5,0.5,0.5,0,0.5,0.5,0.5,0.5,...,0.5,0.5,0.5,0.5,0.5,0,0.5,0.5,0.5,1

In [63]:
X_03.to_csv('income03.csv',index=False)